language: node_js
node_js:
  - 12
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE `sabia-testing`;'
  - (cd packages/api && cp .env.example .env)
install:
  - npx lerna bootstrap
  - (cd packages/api && npm install)
script:
  - npm run lint
  - (cd packages/api && npm run coverage)
  - (cd packages/web && npm run test:visual)
after_script:
  - (cd packages/api && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls)
